# This is a basic workflow to help you get started with Actions

name: OnUpdate

# Controls when the workflow will run
on:
  project:
    types: [created, edited, deleted]

  # Allows you to run this workflow manually from the Actions tab

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pop_msg:
    runs-on: ubuntu-latest
    steps:
      - run: echo "File Updated"
